In [1]:
import pandas as pd
import re

## ČSÚ: Školy a školská zařízení - reálný počet žáků

### Pro rozbor MŠ

Jedná se o oficiální data, kolik dětí docházelo do zařízení.

In [3]:
def get_MS_dochazka(path, sheet='1.1.9'):
    dochazka = (pd.read_excel(path, sheet_name=sheet, header=3, index_col=0, usecols='A, B, C, E, G, I, K')).iloc[3:-1]
    
    rok_match = re.search(r'(\d{4}-\d{2})', path)
    if rok_match:
        year = rok_match.group(1).replace('-', '/')  # Extrahovaný a upravený školní rok
    else:
        year = "Rok nebyl nalezen"
    
    dochazka.insert(loc=6, column='rok', value=year)
    return dochazka

MS_23_24 = get_MS_dochazka(r'..\data\CSU\MS2023-24.xlsx')
MS_22_23 = get_MS_dochazka(r'..\data\CSU\MS2022-23.xlsx')
MS_21_22 = get_MS_dochazka(r'..\data\CSU\MS2021-22.xlsx')
MS_20_21 = get_MS_dochazka(r'..\data\CSU\MS2020-21.xlsx')
MS_19_20 = get_MS_dochazka(r'..\data\CSU\MS2019-20.xlsx')
MS_18_19 = get_MS_dochazka(r'..\data\CSU\MS2018-19_konkrTab.xlsx', sheet='2300421909')


MS_all = pd.concat([MS_23_24, MS_22_23, MS_21_22, MS_20_21, MS_19_20], ignore_index=False, sort=False)
MS_all = MS_all.rename(columns={'Unnamed: 1' : 'Celkem'})
sloupce = ['Celkem', 'mladší 3 let', '3leté', '4leté', '5leté', '6leté a starší']
MS_all[sloupce] = MS_all[sloupce].astype(int)
# MS_all
# MS_18_19

In [4]:
MS_all

,Celkem,mladší 3 let,3leté,4leté,5leté,6leté a starší,rok
Hlavní město Praha,42771,3187,11365,12719,13562,1938,2023/24
Středočeský kraj,52957,3707,13755,15642,16782,3071,2023/24
Jihočeský kraj,23216,2543,5810,6452,6867,1544,2023/24
Plzeňský kraj,19496,1565,4965,5611,6195,1160,2023/24
Karlovarský kraj,8402,911,2220,2418,2537,316,2023/24
...,...,...,...,...,...,...,...
Kraj Vysočina,17965,2421,4637,4931,4984,992,2019/20
Jihomoravský kraj,41796,4271,11050,11898,12162,2415,2019/20
Olomoucký kraj,22931,3436,5913,5914,6068,1600,2019/20
Zlínský kraj,19999,2737,5154,5438,5268,1402,2019/20
Moravskoslezský kraj,39156,5465,9837,10446,11101,2307,2019/20

In [5]:
MS_all.to_csv(r'..\output_files\MS_all_dochazka.csv', mode='w')

### Počet cizinců ve školkách
Počet cizinců v MŠ je již zahrnut MS_all

1) údaje o fyzických osobách (každé dítě je evidováno jen pod jedním státním občanstvím, pokud má dítě dvojí občanství, upřednostní se české, dále občanství státu EU)

In [6]:
dochazka_cizinci = (pd.read_excel(r'..\data\CSU\MS2023-24.xlsx', sheet_name='1.1.15', header=3, index_col=0, usecols='A, H:L')).drop(labels='Česká republika')
dochazka_cizinci

                      2019/20  2020/21  2021/22  2022/23  2023/24
Hlavní město Praha       4701     4805     4893     6222     6258
Středočeský kraj         1816     1793     1891     3022     3104
Jihočeský kraj            485      470      474      959      931
Plzeňský kraj             804      807      837     1338     1324
Karlovarský kraj          489      457      394      670      612
Ústecký kraj              633      625      631     1197     1150
Liberecký kraj            479      478      441      795      755
Královéhradecký kraj      342      319      295      722      634
Pardubický kraj           370      332      332      676      632
Kraj Vysočina             222      225      211      529      577
Jihomoravský kraj         939      911      958     1518     1574
Olomoucký kraj            201      191      220      525      510
Zlínský kraj              146      144      186      482      460
Moravskoslezský kraj      315      307      340      912      888